services:
  # API - API Server for game
  api:
    build:
      context: $APIDIR
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - primary-network
    ports:
      - "8083:443"
      - "8090:80"
    volumes:
    - ./api:/go/src/sitterserver