services:
  # MongoDB
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - primary-network
    ports:
      - 27017:27017
    volumes:
      - $DOCKERDIR/appdata/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: DB_USER
      MONGO_INITDB_ROOT_PASSWORD: DB_PASSWD

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks:
      - primary-network
    ports:
      - 8085:8085
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: DB_PASSWD
      ME_CONFIG_MONGODB_URL: mongodb://DB_USER:DB_PASSWD@mongodb:27017
      VCAP_APP_PORT: 8085
      PORT: 8085
    depends_on:
      - mongodb
