env: "dev" # окружение сервера. Варианты: local, dev, prod
storage_path: "DB_PATH" # адрес для подключения к MongoDB
storage_passwd: "DB_PASSWD" # пока не используется
http_server:
  address: "0.0.0.0:8083"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s