env: "local" # окружение сервера. Варианты: local, dev, prod
storage_path: "./storage/storage.db" # путь к файлу БД или адрес для подключения. SQLite создаст новый файл БД, если не найдет существующий
storage_passwd: "DB_PASSWD" # не используется в SQLite
modules_path: "./modules/modules.json" # путь к файлу с вопросами и ответами
log_path: "LOG_FILE_PATH" # путь к файлу логов
http_server:
  address: "localhost:8083"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s