env: "local" # окружение сервера. Варианты: local, dev, prod
storage_path: "mongodb://mongo:27017/" # адрес для подключения к MongoDB
storage_user: "DB_USER" # пользователь для аутентификации в MongoDB
storage_passwd: "DB_PASSWD" # пароль для аутентификации в MongoDB
cert_path: "CERT_PATH" # путь к файлу ssl сертификата
cert_key_path: "CERT_KEY_PATH" # путь к файлу ключа ssl сертификата
auth_user: "admin"
auth_passwd: "AUTH_PASSWD"
http_server:
  address: "localhost:80"
  addressTLS: "localhost:443"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s