export const MOODULEONE = {
    TITLE: 'Модуль 1. Подготовка',
    TOTALCOUNTS: 20,
    PREIMAGE: 'preimage-one',
    MINCUTE: 'mincut',
    BALOON: 'balloon',
    LISTBLANK: 'listblank',
    LISTFULL: 'listfull',
    CHECKBOXON: 'checkboxon',
    CHECKBOXOFF: 'checkboxoff',
    BACKGROUNDS: {
        ROOMVIEWONE: 'roomviewone',
        ROOMVIEWTWO: 'roomviewtwo',
        KITCHEN: 'kitchen',
        COMPUTER1: 'computer1',
        COMPUTER2: 'computer2',
        HUB: 'HUB',
        PHONEONE: 'phoneone',
        ONSOFA: 'onsofa',
        CALLONE: 'callone',
        CALLTWO: 'calltwo',
        PHONETWO: 'phonetwo',
        ROOMRIGHT: 'roomright',
        BLURROOM: 'blurroom',
    },
    AUDIO: {
        KEYBOARD: 'keyboard',
        MESSAGE: 'message',
        KNOPKA: 'knopka',
        COMPLETE: 'complete',
        CALL: 'call',
    }
}