export const MOODULEONE = {
    TITLE: 'Модуль 1. Подготовка',
    TOTALCOUNTS: 15,
    PREIMAGE: 'preimage-one',
    MINCUTE: 'mincut',
    BALOON: 'balloon',
    LISTBLANK: 'listblank',
    LISTFULL: 'listfull',
    CHECKBOXON: 'checkboxon',
    CHECKBOXOFF: 'checkboxoff',
    LISTMEMORY: 'listmemmory',
    INVENTARY: 'inventary',
    BACKGROUNDS: {
        ROOMVIEWONE: 'roomviewone',
        ROOMVIEWTWO: 'roomviewtwo',
        KITCHEN: 'kitchen',
        COMPUTER1: 'computer1',
        COMPUTER2: 'computer2',
        HUB: 'HUB',
        PHONEONE: 'phoneone',
        ONSOFA: 'onsofa',
        CALLONE: 'callone',
        CALLTWO: 'calltwo',
        PHONETWO: 'phonetwo',
        ROOMRIGHT: 'roomright',
        BLURROOM: 'blurroom',
        TOYSGAME: 'toysgame',
        BAG: 'bagBG',
    },
    COLLECTONE: {
        title: 'title',
        blank: 'blank',
        neck: 'neck',
        bone: 'bone',
        milk: 'milk',
        plain: 'plain',
        hat: 'hat',
        food: 'food',
        misk: 'misk',
        photo: 'photo',
        bag: 'bag',
        baloon1: 'balloon-2',
        baloon2: 'balloon-3',
        trash: 'trash',
        scissors: 'scissors',
        povodok: 'povodok',
        shetka: 'shetka',
        tabs: 'tabs',
    },
    TOYSGAME: {
        title: 'title2',
        frisbitext: 'frisbitext',
        frisbiicon: 'frisbiticon',
        vorottext: 'vorottext',
        voroticon: 'voroticon',
        toytext: 'toytext',
        toyicon: 'toyicon',
        cunttext: 'cunttext',
        cunticon: 'cunticon',
        kongtext: 'kongtext',
        kongicon: 'kongicon',
    },
    AUDIO: {
        KEYBOARD: 'keyboard',
        MESSAGE: 'message',
        KNOPKA: 'knopka',
        COMPLETE: 'complete',
        CALL: 'call',
    }
}